#! /usr/bin/env python3
#   script generated by source_obsnum.sh
import os
import sys

from lmtoy import runs

project="2024-S1-DX-2"

# Dictionary of sources, each with a list of obsnum's in this project
# negative obsnums are ignored in the combinations. See also comments.txt
# for obsnum specific comments and parameters!
on = {}

on["3i_Atlas"] = \
 [ 147940, 147942, 147944,]

# parameters for the first pass of the pipeline (restart=1 is automatically enforced here)
pars1 = {}

pars1["3i_Atlas"] = "qagrade=3"

# parameters for the (optional) second pass of the pipeline (e.g. for bank=0)
pars2 = {}

pars2["3i_Atlas"] = ""

# parameters for the (optional) third pass of the pipeline (usually for bank=1)
pars3 = {}

pars3["3i_Atlas"] = ""

# Found 1 source(s) for 2024-S1-DX-2

if __name__ == "__main__":
    runs.mk_runs(project, on, pars1, pars2, pars3, sys.argv)

# see also /nese/toltec/dataprod_lmtslr/work_lmt/tmp/2024-S1-DX-2.obsnums.log
